# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2945543b4c7584708ccdcf8df1dd065"
name = "last-offer-app"
handle = "last-offer-app-1"
application_url = "https://prediction-problem-uncle-hat.trycloudflare.com"
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://prediction-problem-uncle-hat.trycloudflare.com/auth/callback",
  "https://prediction-problem-uncle-hat.trycloudflare.com/auth/shopify/callback",
  "https://prediction-problem-uncle-hat.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
